GingerPrivacy/GingerWallet

WalletWasabi.Daemon/Config.cs, WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs, WalletWasabi/JsonConverters/NetworkJsonConverterNg.cs
This PR doesn't allow the client to be run on TestNet as there is no server for it.
=> disable testnet

README.md
Still lot to do around this file.
=> README update II

WalletWasabi.Fluent/Extensions/ObservableExtensions.cs, WalletWasabi.Fluent/Helpers/LambdaComparer.cs, WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs, WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListItem.cs, WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Coins/PocketViewModel.cs
This PR ports the changes from Wasabi that fixes unnecessary updates in lists.
https://github.com/WalletWasabi/WalletWasabi/pull/13175
=> [UI] Review EditDiff usage

WalletWasabi.Fluent/Styles/SettingsLayout.axaml
Ports a minor UI fix for settings from Wasabi.
https://github.com/WalletWasabi/WalletWasabi/pull/13166
=> [UI] Set width for TextBox in SettingsLayout

WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
Ports a fix from Wasabi so Tor value is now displayed correctly when set from program arguments.
https://github.com/WalletWasabi/WalletWasabi/pull/13178
=> [UI] Use the correct setting

WalletWasabi.Fluent/Behaviors/CheckMarkVisibilityBehavior.cs, WalletWasabi.Fluent/Controls/TextBox.axaml, WalletWasabi.Fluent/Styles/Checkmark.axaml, WalletWasabi.Fluent/Styles/TextBox.axaml
Ports changes from Wasabi that moves the checkmark into the PW box.
https://github.com/WalletWasabi/WalletWasabi/pull/13177
=> [UI] move pw checkmark into the control

WalletWasabi.Fluent/Extensions/ObservableExtensions.cs, WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs, WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
=> Partially revert

WalletWasabi.Fluent/Icons/Icons.axaml, WalletWasabi.Fluent/Styles/Themes/Base.axaml, WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs, WalletWasabi.Fluent/ViewModels/HelpAndSupport/DocsLinkViewModel.cs
to point to the proper ginger pages
=> About window update

WalletWasabi.Daemon/Config.cs, WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs, WalletWasabi.Fluent/Extensions/FriendlyExceptionMessageExtensions.cs, WalletWasabi.Fluent/Screenshot/Capture.cs, WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs, WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs, WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs, WalletWasabi.Fluent/ViewModels/HelpAndSupport/BugReportLinkViewModel.cs, WalletWasabi.Fluent/ViewModels/HelpAndSupport/UserSupportViewModel.cs, WalletWasabi.Fluent/ViewModels/MainViewModel.cs, WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenFileViewModel.cs, WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/PayNowAssistantMessageViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletVerifyRecoveryWordsViewModel.cs, WalletWasabi/BitcoinCore/CoreNode.cs, WalletWasabi/BitcoinCore/P2pNode.cs, WalletWasabi/Services/UpdateManager.cs, WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs, WalletWasabi/Wallets/SpecificNodeBlockProvider.cs
Only UI and exceptions ( + download link, + default png name)
=> Change Wasabi to Ginger Wallet

WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
=> Do not trim zeros for suggested btc amounts to avoid change

WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs, WalletWasabi.Fluent/Models/Wallets/CoinModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
=> fix CoinModel design issue

WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs, WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs, WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
=> make sure coins are updated when selecting a wallet

WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs
=> do not rely on reactive code

WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/Decomposer.cs
https://github.com/WalletWasabi/WalletWasabi/pull/13260
https://github.com/WalletWasabi/WalletWasabi/pull/13272
=> Wasabi decompose fixes and tests

Directory.Packages.props, WalletWasabi.Backend/WalletWasabi.Backend.csproj, WalletWasabi.Daemon/WalletWasabi.Daemon.csproj, WalletWasabi.Daemon/packages.lock.json, WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj, WalletWasabi.Fluent.Desktop/packages.lock.json, WalletWasabi.Fluent/WalletWasabi.Fluent.csproj, WalletWasabi.Fluent/packages.lock.json, WalletWasabi.Packager/WalletWasabi.Packager.csproj, WalletWasabi.Packager/packages.lock.json, WalletWasabi.Tests/WalletWasabi.Tests.csproj, WalletWasabi/WalletWasabi.csproj, WalletWasabi/packages.lock.json
Vulnerability update.
The package is added directly.
=> System.Text.Json update

WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Client/PaymentAwareOutputProviderTests.cs, WalletWasabi/WabiSabi/Client/Batching/PaymentAwareOutputProvider.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/AmountDecomposer.cs, WalletWasabi/WabiSabi/Client/OutputProvider.cs
During the denomination level creation the client shouldn't take account that their inputs have fee exemptions or not since it can lead to different denomination levels than the other clients' denomination levels.
=> Denomination fee exemption fix

WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs, WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs, WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/ManualCoinJoinProfileViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/SpeedyCoinJoinProfileViewModel.cs, WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinSettingsViewModel.cs, WalletWasabi.Fluent/ViewModels/Dialogs/NewWalletAdvancedOptionsDialogViewModel.cs, WalletWasabi.Fluent/Views/Dialogs/AdvancedCoinjoinOptionsView.axaml, WalletWasabi.Tests/UnitTests/WabiSabi/Client/IsRoundEconomicTests.cs, WalletWasabi/Blockchain/Keys/KeyManager.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs, WalletWasabi/Wallets/IWallet.cs, WalletWasabi/Wallets/Wallet.cs
Option in the coinjoin settings: below this fee rate no median fee rate check is needed, good to coinjoin.
=> Safe mining fee rate

README.md, WalletWasabi.Backend/InitConfigStartupTask.cs, WalletWasabi.Backend/Startup.cs, WalletWasabi.Daemon/WasabiApplication.cs, WalletWasabi.Fluent/CrashReport/Views/CrashReportWindow.axaml, WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs, WalletWasabi/BuyAnything/BuyAnythingManager.cs, WalletWasabi/Services/SingleInstanceChecker.cs, WalletWasabi/Services/Terminate/TerminateService.cs, WalletWasabi/Tor/TorSettings.cs
Wasabi -> Ginger/client string replacement
Adding CoinjoinError messages
=> Minor changes - CoinJoinError messages, Wasabi string replace

WalletWasabi.Documentation/WasabiCompatibility.md, WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs, WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs, WalletWasabi/Hwi/Models/HardwareWalletModels.cs, WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
=> Update hwi to 3.1.0

WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Later more sophisticated solution will come.
=> Client side coinjoin detection

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs, WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateHolder.cs, WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
Moving the RoundState consistency checks from the RoundStateUpdater to the RoundStateHolder
=> RoundStateHolder checks
